//
// Created by zlhartma on 1/7/2023.
//

#ifndef NEURAL_NETWORK_VISUALIZER_CONSTANTS_H
#define NEURAL_NETWORK_VISUALIZER_CONSTANTS_H

#define DEFAULT_SAVE_PATH PREFIX(R)"C:/"

#endif //NEURAL_NETWORK_VISUALIZER_CONSTANTS_H
